// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginReq struct {
	Phone                []byte   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	VerifyInfo           []byte   `protobuf:"bytes,3,opt,name=verify_info,json=verifyInfo,proto3" json:"verify_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetPhone() []byte {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *LoginReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LoginReq) GetVerifyInfo() []byte {
	if m != nil {
		return m.VerifyInfo
	}
	return nil
}

type LoginRsp struct {
	Errinfo              *Errorinfo `protobuf:"bytes,1,opt,name=errinfo,proto3" json:"errinfo,omitempty"`
	Id                   uint32     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Token                []byte     `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetErrinfo() *Errorinfo {
	if m != nil {
		return m.Errinfo
	}
	return nil
}

func (m *LoginRsp) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginRsp) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type ZoneGetReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneGetReq) Reset()         { *m = ZoneGetReq{} }
func (m *ZoneGetReq) String() string { return proto.CompactTextString(m) }
func (*ZoneGetReq) ProtoMessage()    {}
func (*ZoneGetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ZoneGetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneGetReq.Unmarshal(m, b)
}
func (m *ZoneGetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneGetReq.Marshal(b, m, deterministic)
}
func (m *ZoneGetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneGetReq.Merge(m, src)
}
func (m *ZoneGetReq) XXX_Size() int {
	return xxx_messageInfo_ZoneGetReq.Size(m)
}
func (m *ZoneGetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneGetReq.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneGetReq proto.InternalMessageInfo

type ZoneGetRsp struct {
	Errinfo              *Errorinfo `protobuf:"bytes,1,opt,name=errinfo,proto3" json:"errinfo,omitempty"`
	List                 []*Zone    `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ZoneGetRsp) Reset()         { *m = ZoneGetRsp{} }
func (m *ZoneGetRsp) String() string { return proto.CompactTextString(m) }
func (*ZoneGetRsp) ProtoMessage()    {}
func (*ZoneGetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *ZoneGetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneGetRsp.Unmarshal(m, b)
}
func (m *ZoneGetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneGetRsp.Marshal(b, m, deterministic)
}
func (m *ZoneGetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneGetRsp.Merge(m, src)
}
func (m *ZoneGetRsp) XXX_Size() int {
	return xxx_messageInfo_ZoneGetRsp.Size(m)
}
func (m *ZoneGetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneGetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneGetRsp proto.InternalMessageInfo

func (m *ZoneGetRsp) GetErrinfo() *Errorinfo {
	if m != nil {
		return m.Errinfo
	}
	return nil
}

func (m *ZoneGetRsp) GetList() []*Zone {
	if m != nil {
		return m.List
	}
	return nil
}

type Zone struct {
	Country              []byte   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Zone                 []byte   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetCountry() []byte {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *Zone) GetZone() []byte {
	if m != nil {
		return m.Zone
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "user_proto.login_req")
	proto.RegisterType((*LoginRsp)(nil), "user_proto.login_rsp")
	proto.RegisterType((*ZoneGetReq)(nil), "user_proto.zone_get_req")
	proto.RegisterType((*ZoneGetRsp)(nil), "user_proto.zone_get_rsp")
	proto.RegisterType((*Zone)(nil), "user_proto.zone")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x24, 0x69, 0xb4, 0xf8, 0x12, 0x8b, 0x2c, 0x0a, 0x8b, 0x17, 0xc3, 0xe2, 0x21, 0xa7, 0x08,
	0xd5, 0x9f, 0xf0, 0xba, 0x07, 0xaf, 0x81, 0xb6, 0x2f, 0x75, 0xb1, 0xdd, 0x17, 0x5f, 0xb6, 0x42,
	0xfc, 0x7a, 0xd9, 0x97, 0x54, 0x73, 0xf6, 0x36, 0xb3, 0x33, 0xcc, 0xcc, 0x3e, 0x80, 0x53, 0x8f,
	0x5c, 0x77, 0x4c, 0x81, 0x94, 0xe0, 0x46, 0xf0, 0x7d, 0xb1, 0xa5, 0xe3, 0x91, 0xfc, 0xa8, 0x98,
	0x37, 0xb8, 0x3a, 0xd0, 0xde, 0xf9, 0x86, 0xf1, 0x53, 0xdd, 0xc2, 0x45, 0xf7, 0x4e, 0x1e, 0x75,
	0x52, 0x26, 0x55, 0x61, 0x47, 0xa2, 0x14, 0x64, 0x61, 0xe8, 0x50, 0xa7, 0x65, 0x52, 0x5d, 0x5b,
	0xc1, 0xea, 0x01, 0xf2, 0x2f, 0x64, 0xd7, 0x0e, 0x8d, 0xf3, 0x2d, 0xe9, 0x85, 0xf8, 0x61, 0x7c,
	0x7a, 0xf5, 0x2d, 0x99, 0xcd, 0x6f, 0x6e, 0xdf, 0xa9, 0x27, 0x58, 0x22, 0xb3, 0x38, 0x63, 0x72,
	0xbe, 0xbe, 0xab, 0xff, 0x06, 0xd5, 0xc8, 0x4c, 0x22, 0xda, 0xb3, 0x4b, 0xad, 0x20, 0x75, 0xbb,
	0xa9, 0x30, 0x75, 0xbb, 0x38, 0x2c, 0xd0, 0x07, 0xfa, 0xa9, 0x68, 0x24, 0x66, 0x05, 0xc5, 0x37,
	0x79, 0x6c, 0xf6, 0x18, 0xe2, 0x7c, 0x83, 0x73, 0xfe, 0x9f, 0xda, 0x47, 0xc8, 0x0e, 0xae, 0x0f,
	0x3a, 0x2d, 0x17, 0x55, 0xbe, 0xbe, 0x99, 0xbb, 0x63, 0xb0, 0x15, 0xd5, 0xbc, 0x40, 0x16, 0x99,
	0xd2, 0xb0, 0xdc, 0xd2, 0xc9, 0x07, 0x1e, 0xa6, 0x7b, 0x9d, 0x69, 0xbc, 0x58, 0x74, 0xc8, 0x07,
	0x0a, 0x2b, 0x78, 0x73, 0x29, 0x39, 0xcf, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x9f, 0x45,
	0x78, 0x97, 0x01, 0x00, 0x00,
}
